### ISSUE TITLE
[Package] Instructions incomplete: wrong control file location is used

### ISSUE THREAD

**Issue by wknoben** [bartvanosnabrugge/summaWorkflow_public#10]
Current readme says to update
1. cwarhm_summa_folder
2. results_folder_path , to match the root_path in the control file
3. test_data_path , path to the test data, if you want to skip the data download workflow steps (by default)
4. reset_test to True (default), this is a flag that starts a new run (and deletes all data from any results folder), and restarts by copying the test data to the results folder or False: continue with existing data in the results folder.

However, `test_bow_at_banff.py` reads control info from a hard-coded location users are not told to update: https://github.com/bartvanosnabrugge/summaWorkflow_public/blob/bebe235d5bb8742b13d294db733b61f03b042f41/workflows/summa_bowatbanff/test_bow_at_banff.py#L20

Suggest to change this line to:
```
control_options = utl.read_summa_workflow_control_file(os.path.join(cwarhm_summa_folder,'0_control_files/control_Bow_at_Banff_test.txt'))
```
or update `README.rst`.

**Comment by bartvanosnabrugge** [comment]
I updated that line and moved the reading of the control file to after the reset, so that the right file is read.
